---
title: "Comments for the author"
output: pdf_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section Editor

Thank you for this submission.
I, and the two reviewers, all agree that this has the potential to be a very useful piece for the community and likely will be highly cited.
Both reviewers offer some constructive suggestions -- Reviewer 2's are fairly minor.
Reviewer 1's are more in-depth, but I strongly suggest you implement R1's suggestions.
I concur with the view that you may not need to define landscape ecology given the target journal.
I think adding some of the detail that R1 asks for in terms of descriptions of the packages and recommendations would be a very useful thing to add.
Both reviewers also commented about the survey.
I am less concerned about your addressing those issues, as I do not see the survey as being core to the paper -- although some interpretation of the questions that R1 asks would be worth reflecting on, and a little more detail on the survey reach, as asked by R2 would be good to include.

**Reply**: Thank you very much for considering the manuscript for publication. 
We appreciate the reviewers comments and think they all help to improve the manuscript.
We agree with reviewer 1 that the definition of landscape ecology could be shortened given the target audience of the journal. 
Thus, the introduction now puts a stronger focus on advantages of open-source software and especially R. 
Furthermore, we added explanations for all packages that were missing in the original submission as suggested by reviewer 1.
However, we think that given recommendations which packages to use is very difficult for several reasons. 
First, packages have different advantages and disadvantages that differ depending on e.g., the research question, the available data, or the personal preferences and experiences of the users.
Second, we believe that trying out several packages for similar task can actually beneficial and strengthen trust in the method.
But, by modifying Figure 1 and adding Box 1 we hope to give some more guidelines on how to organize an analysis.
We agree that the survey is not the core of the paper, nevertheless, the comments by both reviewers are very valuable and improve the conclusions we can draw from it. 
Thus, we added some explanation about the survey reach and what this means for the results of the survey. \vskip 0.5cm

In my own read of the paper, I wondered if the development of some sort of typology of the available tools (as Rayfield et al. 2011 did for connectivity tools) would be useful.
I also suggest you consider some "boxes" that give point-by-point information.
I would love to see a "Where to start" box for total beginners and then maybe a second one with "Tips for developers".
In addition, can you please better explain the tidyverse to the readers?
It would also be useful if you could just elaborate a little bit in the annotated references for some of the key papers, as has been done for most of the papers published in this journal.

**Reply**: We agree that the approach of Rayfield et al. 2011 is great, but we also want to point out that it was developed for a more specific domain (i.e., connectivity), while this manuscript deals with the whole field of landscape ecology.
Thus, we believe that a similar typology for all packages included in this manuscript would be too complicated to be of actual help.
Thank you for this great idea to add boxes. 
We added a box "Where to start" to give some major steps how to approach landscape ecology in R for novice users. 
We hope this will also at least partly address the issue raised by reviewer 1 about recommendations.
We also thought about a second box for mode advanced users and even developers, but decided that the target audience of the paper are most likely novice to intermediate R users and not developers and the topic of developing own packages specifically for the landscape ecology community could maybe be a future manuscript.
Also, we added a short explanation of the tidyverse and its strength.
Lastly, we provide more information about the annotated references.
\vskip 0.5cm

I hope you find these comments helpful.
With a little more revision, I am quite confident that the paper can be accepted in Current Landscape Ecology reports.
Thank you, and I look forward to receiving a revised manuscript!

**Reply**: Again, thank you very much for the appreciated and valuable suggestions for improving the manuscript and we hope that the revised manuscript improved compared to the previous version with help of the reviewers. 
All changes to the manuscript are indicated by the blue color. \vskip 0.5cm 

## Reviewer 1

I think the idea of a review of R tools for landscape ecology workflows is a great one, but this manuscript suffers a bit from lack of clarity of purpose.
If it's for landscape ecologists, as the choice of journal suggests, defining landscape ecology seems unnecessary, but a bit more information on R in general and why a landscape ecologist might choose R rather than some other tool would be useful.

**Reply**: Thank you for the general encouraging words about the manuscript. 
We agree that such a long definition of landscape ecology is not needed given the target audience of the journal. 
Thus, we shortened the introduction related to landscape ecology in general and rearranged other sections of the introduction.
Most of the introduction now introduces the advantages and strength of open-source software and in particular R. While all of the authors are enthusiastic R users, we think that a comprehensive discussion of R vs. other open-source software is outside of the scope of this paper and more important not expedient in general since other software might work better for other people (e.g., Python). \vskip 0.5cm

I'm reading this manuscript from the perspective of a very experienced user of R for geospatial analyses, and who has spent a lot of time teaching students and post-docs how to do so.
I am familiar with nearly all of the packages mentioned, and even I found the lists of packages with little explanation or information overwhelming.
Why would I use one or another?
Do they have good documentation?
What capabilities might I need from other software?
Have you used all the packages mentioned, or simply compiled lists?

**Reply**: All authors of the manuscript are experienced R users with many years of experience using the programming language. 
Additionally, all authors even contributed several packages to the community themselves. 
Given the different background of all authors, collectively probably most packages were used by at least one of the authors, but probably not all. 
Nevertheless, we also believe that this is not necessarily important for this review. 
Furthermore, we agree with the reviewer that more specific recommendation which package to use could be useful, however, we also think that this is very difficult. 
Reasons for this include, besides others, personal preferences of the users or analysis specific circumstances. 
Lastly, the review should be as neutral as possible without favoring one package over another because pros and cons of package differ between users and all were developed with a specific idea in mind.
But, we think that our new "Box 1: Where to start" hopefully can assist novice users with their workflow. \vskip 0.5cm

And, mentioned but not elaborated on: How would I combine these into an effective workflow, making my landscape ecology research easier and more reproducible?

**Reply**: We hope that the modified Figure 1, the added Box 1 and some added explanation in the conclusions explain how using R can facilitate a reproducible workflow in landscape ecology. \vskip 0.5cm

1.1 I am a bit impressed but also surprised that you chose to define landscape ecology without using the word "pattern."

**Reply**: While there are certainly many ways to define landscape ecology, we agree that pattern is a central term and included it in the introduction. \vskip 0.5cm

"it has no internal support for reading, processing, or visualizing spatial data" This is misleading - these capabilities are part of well-developed and maintained packages, consonant with the R philosophy and structure.

**Reply**: We agree with the reviewer that this sentence might be misleading. 
We tried to reword the statement in a way that makes clear base R does not have these capabilities, but many package provide it. \vskip 0.5cm

Because of the lack of clear objective and audience, the manuscript is a mix of overexplanation and complex concepts dropped without adequate explanation.
Some examples of underexplained concepts:

**Reply**: Thank you for this valuable remark. We tried to add additional explanations to concepts which might be underexplained to especially novice users which hopefully increases the value of the manuscript. \vskip 0.5cm

"Packages that deal with such issue include groundhog [42], packrat [43], or renv [44]. For more information about R package development in general, see [40]." How do they do so?
Why does it matter?

**Reply**: We agree that it was not clear enough how these package could help with reproducibility, thus we added a more detailed explanation. \vskip 0.5cm

"also integrates into the widely used tidyverse packages" Which are what, and why should the reader care?

**Reply**: Thank you for pointing out that any further explanation is missing. 
We added a brief explanation of what the tidyverse is and why using it can be beneficial. \vskip 0.5cm

"Finally, there are a number of tools for landscape ecology implemented in GIS software, such as r.li or r.pi for GRASS GIS [69,70,37], terrain analysis methods in SAGA GIS [71], or morphological operations for Google Earth Engine. It is possible to control several GIS software directly from R using dedicated packages, such as rgrass7 [72] for GRASS GIS, RSAGA [73] for SAGA GIS, and rgee [66] for Google Earth Engine." This should be expanded on.
How can R fit into a workflow using these GIS tools, and why would you want to?

**Reply**: We added an explanation how these package allow to incorporate functionality currently only available in GIS software into reproducible and shareable R scripts. \vskip 0.5cm

The section on CRS and projections should discuss the recent major changes to PROJ and thus to R packages relying on it.
A lot of the information that appears online is now obsolete.

**Reply**: We added an explanation of the recent changes to PROJ and make users aware to pay attention if old Proj4 strings are used. 
Furthermore, we advise to use ESPG codes for CRS. \vskip 0.5cm

In some places the formatting is problematic, such as automatic hyphenation of R package names resulting in "random-Forest" instead of "randomForest".

**Reply**: We agree that this is problematic and we weren't even aware this is happening so thanks for pointing it out. 
We deactivated the automatic hyphenation by LaTeX. \vskip 0.5cm

Table 1 is very useful, but does not contain all the packages mentioned in the text.

**Reply**: Thank you for checking the table so extensively. 
We made sure all packages should be included now. 
We also added the information to the table caption that not all packages from the manuscript are included but only packages specifically designed for spatial data and landscape ecology. \vskip 0.5cm

Survey: do you think the survey results reflect the true state of affairs, or do they reflect lack of training/knowledge/the fragmented nature of the R community?

**Reply**: We added that we aware that the survey is most likely not representative for the R community and R users due to how we tried to reach the community and also due to the questions asked in the survey. 
Since the survey is not the main idea of the manuscript though, we think that the survey still might be interesting even with these shortcomings. \vskip 0.5cm

"However, since landscape ecology constantly develops and improves, the R programming language and its packages need to change and adapt to these changes." That is indeed a strength of the R community, though the way it is stated here implies that this is not true.
Instead, the problem is that there are so many packages, and constantly more being added.

**Reply**: We agree that the sentence implied that the R community is not constantly adapting to the new developments of landscape ecology which is certainly not true. 
We reworded the sentence making clearer that indeed the community constantly improves the R programming language. 
However, we do not agree with the reviewer that "[...] the problem is that there are so many packages [..]".
Even though we acknowledge that the amount of package can be overwhelming, especially for novices users, diversity of packages is a big strength - even for similar specific tasks. 
Possible advantages include e.g., the possibility to compare different implementations of similar/identical task or providing functionality for slightly different data structures. \vskip 0.5cm

"Because it is possible to import, modify, analyze, and visualize spatial data all in the same programming environment, R allows for transparent and reproducible workflows."
But the authors do not mention any tools for facilitating reproducibility.
This is a huge part of why R should be more widely used, and should be expanded upon.

**Reply**: We highly agreed that this one of the main reasons why R should be widely used and we added an explanation how the script-based character of R itself allows to share and reproduce analysis. \vskip 0.5cm

Furthermore, the survey showed the that many members of the landscape ecology community actively develop R packages themselves, demonstrating that tools are constantly added and updated.
Yes, agreed.
So why imply not, as called out above?

**Reply**: Please see our reply to the previous comment. 
We reworded the sentence to state clearer that this is indeed one of the strength of the R community. \vskip 0.5cm

"While the R programming language is generally well suited to handle, analyze and visualize spatial data, the increasing availability of large data sets also leads to the challenges of increased computational demands, in terms of computational time as well as memory requirements, the R programming language has to face." Which are?
I know, but the casual reader may not.
How could the R core team improve capabilities?
What efforts are underway?
How do existing packages, notably raster and terra, deal with this?
Are there tools to help parallelize landscape ecology workflows?
This problem statement without any discussion or resolution might turn landscape ecologists away from R as a tool.

**Reply**: We added some explanation that raster and terra already provide solutions to this issue by processing only chunks that can be stored in memory. 
Additionally, we added some information about parallel processing as another possible solution to these issues. 
However, we believe that discussing underlying issues of R's memory management is outside the scope if this paper. \vskip 0.5cm

There *are* reasons one might choose tools other than R, or alongside R.
This review doesn't really articulate what the pros and cons are.

**Reply**: We agree with the reviewer that there are many reasons to use other software or programming languages. 
Nevertheless, we think that the scope of this review is not to discuss pro and cons between the different tools, but rather to focus on R. 
At the same time, we believe that the manuscript does give many arguments why R might be a good solution for many tasks. \vskip 0.5cm

The reference section gives no journal names.
That can't be right.

**Reply**: We apologize for this. 
The manuscript was written using the rticles packages with the corresponding template for Springer journals, which somehow did not include journal names. 
We fixed the citation style including journal names. \textcolor{red}{STILL NEED TO DO THIS ACTUALLY!} \vskip 0.5cm

I took a look at a 2019 review of R packages for a particular discipline that was cited in this paper (Joo et al, J. Animal Ecology).
Beyond simply listing packages, the authors looked at their documentation, whether they were actively maintained, and suggested how those packages might fit into a workflow.
Their Figure 1 provides an illustration of the workflow, and helps to put the package list in their Table 1 into a sensible context.
Something similar would work well here, and help to make sense of the overwhelming possibilities.

**Reply**: We agree with the reviewer that Figure 1 of Joo et al. places the packages nicely into a context. We tried to achieve something similar with our Figure 1 as well, but obviously failed to achieve this goal. Thus, we tried to improve Figure 1 in the revised version of the manuscript to highlight better how the packages could be placed in a workflow. Also, we added an explanation that only packages were included that were available on CRAN at the time of preparation of the manuscript, which ensures at least that packages are maintained to fulfill all technical requirements by CRAN. \vskip 0.5cm

Can you give any recommendations?
There are a LOT of packages dealing with all aspects of landscape ecology, including aspects not covered here.
How can landscape ecologists learn of existing packages and new developments?
How can they choose among similar packages?

**Reply**: We are aware that there a many packages listed in this manuscript which might be overwhelming, especially given that some packages cover similar tasks. 
We hope that especially Box 1, but also the restructured Figure 1 help landscape ecologists to find suitable packages. 
Furthermore, we think that the structure in Table 1 actually helps to find packages related to specific task. 
Lastly, we think that trying out similar packages for the same task can actually be beneficial, as also added to Box 1. \vskip 0.5cm

How can they put together packages to develop a reproducible workflow, and how can they document and share that?

**Reply**: We hope that the modified Figure 1, the added Box 1 and some added explanation in the conclusions explain how using R can facilitate a reproducible workflow in landscape ecology. \vskip 0.5cm

The script provided in the appendix is both not useful for experienced R users, and not well-enough documented for novices.

**Reply**: We agree with the reviewer that the provided script is not used for experienced R users and targeted to novices.
Thus, we tried to improve the the documentation of the code. \vskip 0.5cm

The viridis package appears here, but is never mentioned or explained.
ggplot graphics are used, but that is a large and complex field.
While the caption to the associated Figure 2 mentions base vs ggplot graphics, and a subsequent paragraph goes into more detail, the distinction isn't really clear.

**Reply**: We agree that the use of viridis might be confusing without mentioning it in the manuscript and we removed it from the R script.
We agree that ggplot2 graphics are a very large field.
This also highlights that it is outside the scope of this paper.
Nevertheless, ggplot2 is used quite frequently by the R community, so we decided to include it in the example.
We added an explanation how base R maps and ggplot2 maps differ in their underlying synthax and capabilities. 
Also, we added a reference to the manuscript pointing towards ggplot2 specific resources. \vskip 0.5cm

I would like to see a really useful review of R tools for landscape ecologists.
There's a lot of potential there, and something that covers both the basic concepts of using R and getting information and the current state of the relevant packages would be of great utility.

**Reply**: We agree with the reviewer and hope that by trying to address the very helpful and valuable comments by the reviewers, we approach this goal to a higher degree. \vskip 0.5cm

## Reviewer 2

The manuscript "Open-source tools in R for landscape ecology" by Maximillian H.K. Hesselbarth, Jakub Nowosad, Johannes Signer and Laura J. Graham (CLER-D-21-00001) is a brief but complete review of the current R packages for landscape ecology studies and their functionality.
The manuscript is well structured as it describes the typical workflow of any landscape ecology study, and details most of the existing R packages to perform these tasks.
I consider this information very useful for those ecologists initiating into the landscape ecology field that would like to analyze landscape data through R.
Finally, the manuscript shows the results of a simple survey to the landscape ecology community that evidence the usage of R for their studies, and exhibit the main points that the community would like to improve for their landscape ecology studies.

I have revised the manuscript and I believe is almost ready for publication.
I have a few comments and suggestions that I believe would clarify some parts of the manuscript, which I detail below.

**Reply**: Thank you very much for the kind and encouraging words about the manuscript.
We are happy to hear that the reviewer thinks the manuscript might be useful for landscape ecologists that would like to analyze data through R. 
We hope by including the appreciated and valuable comments by two reviewers we even increased the usefulness of the manuscript. \vskip 0.5cm

L16: Can't understand the phrase, please clarify: "and lastly, iv) and can guide how to manage these heterogeneous landscapes".

**Reply**: Since both the section editor and reviewer 1 suggested to remove the definition of landscape ecology due to the target audience of the journal, the introduction was rewritten and shorted including this phrase. \vskip 0.5cm

L42: "today the programming language".
Replace "the" with "this".

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L64: Replace "for landscape ecology" with "for landscape ecology studies".

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L76: Replace "therefore, we focus on only the former two in this review" with "therefore, in this review we focus on only the former two".

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L81: Perhaps you can also mention the package devtools .
Although I see that the package remotes is based in devtools.

**Reply**: We agree that many users are used to devtools to install packages from GitHub.
However, we decided to only mention remotes in this context since it is the more recent replacement for this task as also stated on the remotes homepage ("[...] This package is a lightweight replacement of the **install\_** functions in devtools. Indeed most of the code was copied over from devtools [...]" <https://github.com/r-lib/remotes#readme>) \vskip 0.5cm

L241: "Most landscape metrics are a represented by...".
Remove "a".

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L348: "many different generic algorithms to create landscapes can be found across various R packages".
Replace "various" with "a couple" as you mention only two packages in the next sentences.

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L355: Please expand in how you reach the "landscape ecology community".
Did you mail colleagues you already knew?
Did you send the survey to scientists of different parts of the world?
For instance, I personally believe that results may differ depending on the age, or on the country or continent in which the scientist works.
I only suggest to expand on how representative is the survey population of the landscape ecology community, and clarify the scope of it.

**Reply**: We strongly agree with the reviewer that this information would be very valuable to judge the representation of the survey.
However, unfortunately such questions were not included.
We also acknowledge that the survey is most likely not representative for all skill levels of *R* users because we assume that by using mailing list and social media more advanced users were more likely to take part in the survey.
We added and clarified those shortcomings of the survey. \vskip 0.5cm

L357: The link is broken.

**Reply**: The GitHub repository is currently set to "private" and will be publicly available upon publication. \vskip 0.5cm

L361: Correct the commas, as they are inside the quotation marks.

**Reply**: We changed the sentence as suggested. \vskip 0.5cm

L375: Correct the commas, as they are inside the quotation marks.

**Reply**: We changed the sentence as suggested. \vskip 0.5cm
