---
title: "Outline"
output: html_document
theme: cosmo
date: '`r format(Sys.time(), "%d %B, %Y")`'
editor_options: 
  chunk_output_type: console
---

<br/>

Journal: Current Landscape Ecology Reports

Type: Methodological Developments in Landscape Ecology

<br/>

Title: **Open source landscape ecology tools**

Maximillian H.K. Hesselbarth<sup>1</sup>, Jakub Nowosad<sup>2</sup>, ...

<br/>

<sup>1</sup>Department of Ecosystem Modelling, University of Goettingen, Buesgenweg 4, 37077 Goettingen, Germany 

<sup>2</sup>Institute of Geoecology and Geoinformation, Adam Mickiewicz University, Krygowskiego 10, 61-680 Poznan, Poland

*Corresponding author: E-Mail address: maximilian.hesselbarth@uni-goettingen.de

<br/>

Keywords: keyword 1, keyword 2, keyword 3, keyword 4, ...

### 1. Introduction
- Intro to landscape ecology
    - How do landscape characteristics influence ecological processes and vice verse
    - Growing importance because often scales of policy making are adressed
    - Need to preprocess, modify, model and analyze spatial data
    - Short overview over common tasks/analysis in landscape ecology
    - ...
- Intro to open-source
    - What is open-source and why is it advantageous to closed source
    - R environment
    - ...
- Landscape ecology in R
    - One of the most used tools/powerful tool in ecology and spatial data analysis
    - History of landscape ecology/spatial data analysis in R
    - Growing body of specific textbooks and literature; e.g.:
        - "Geocomputation with R"
        - "Spatial Data Science"
        - "Spatial Ecology and Conservation Modeling. Applications with R"
        - "Learning Landscape Ecology. A Practical Guide to Concepts and Techniques"
        - ...
    - Growing body of specific R package for spatial data analysis
    - ...
- Objectives of review
    - Existing/important R packages for landscape ecology
    - Missing packages R packages for landscape ecology
    - ...
- ...

### 2. Existing packages

- Base R
- Basic spatial data
    - Basic data types (i.e. vector vs. raster data)
        - raster, stars, terra(?)
        - sp (+rgeos, rgdal), sf
        - Access to spatial data (e.g. rnaturalearth) (?)
        - ...
- Creating maps
    - tmap, ggplot2
    - mapview, leaflet
    - ...
- Spatial regression
    - nlme
    - spdep, gstat/geoR (spatial autocorrelation), + pgirmess??, (http://www.r-inla.org/download; INLA?? check license)
    - ...
- Spatial statistics?? (point-patterns analysis) // MH:I think that's way too much
    - spatstat (e.g., https://link.springer.com/chapter/10.1007/978-3-030-01989-1_4)
- Ecological analysis
    - Landscape metrics
        - landscapmetrics
        - belg
        - ...
    - Habitat selection and SDM
        - https://link.springer.com/chapter/10.1007/978-3-030-01989-1_7
        - lm(), glm(), gam, rpart, RandomForest (ranger), lme4
        - ade4, adehabitat, sdm
        - some MAXENT package?
        - biomod2??
        - ...
    - Connectivity? 
        - https://link.springer.com/chapter/10.1007/978-3-030-01989-1_9
        - gdistance??
    - Spatial population dynamics
        - https://link.springer.com/chapter/10.1007/978-3-030-01989-1_10
    - Landscape genetics
    - Various
        - vegan
        - dismo
        - NLMR (and RandomFields), landscapetools
        - ecospat?? (https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.02671)
        - PresenceAbsence?? (https://www.jstatsoft.org/article/view/v023i11)
        - ENMeval?? (https://cran.r-project.org/web/packages/ENMeval/index.html)
        - prioritizr?? (https://prioritizr.net/)
        - data sources/API connections?
        - ecodist?? (https://cran.r-project.org/web/packages/ecodist/index.html)
        - LEA?? (http://membres-timc.imag.fr/Olivier.Francois/Frichot_etal_MEE_2015.pdf)
        - remote sensing??
        - agent-based modelling // MH:I think that's way too much
    - ...
- ...
### 3. Missing packages
- First topic
    - First paragraph headline
    - Second paragraph headline
    - ...
- Second topic
    - First paragraph headline
    - Second paragraph headline
    - ...
- ...
- Last topic (often objectives and hypotheses)
    - ...
    
### 4. Discussion
- Possible points to discuss
    - First point
    - Second point
    - ...
- ...
- Conclusions
    - Conclusion 1 
    - Conclusion 2
    - ...
- ...
    
### 5. Acknowledgments
- ...

### Open questions:
- Remote sensing/GIS?
- Landscape genetics?
- Landscape Connectivity?
  - ResistanceGA
  - LQGraph
- Some "results"/meta-analysis of increase of R in landscape ecology?
- Open-source licenses (!!)
- Missing packages
    - surface metrics
    - vector-based metrics
    - Morphological Spatial Pattern Analysis (https://forest.jrc.ec.europa.eu/en/activities/lpa/mspa/)
- ...
