---
title: "Survey's results"
output: 
  html_document:
    code_folding: hide
    toc: true
theme: cosmo
date: '`r format(Sys.time(), "%Y-%m-%d")`'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, fig.align = "center")
options(scipen = 99*99)
# knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(googlesheets4)
library(forcats)
library(stringr)
```

```{r}
# read and prepare --------------------------------------------------------
x = read_sheet("https://docs.google.com/spreadsheets/d/1mV_wZWb4desjdzUWHALIB-uFRCauSTOGSvENsnkiAhI/edit#gid=1189808333")

old_names = names(x)

new_names = c("time", "position", "how_often", "expertise",
              "major_topic", "important_tasks", "data_model",
              "r_packages", "own_package", "own_package_location",
              "missing_methods", "usefulness", "comments")

names(x) = new_names
```

Number of answers - `r nrow(x)`.

# `r old_names[2]`

```{r}
# position
ggplot(x, aes(y = fct_infreq(position))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[2])
```


# `r old_names[3]`

```{r}
# how_often
ggplot(x, aes(y = fct_infreq(how_often))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[3])
```

# `r old_names[4]`

```{r}
# expertise
ggplot(x, aes(y = fct_infreq(expertise))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[4])
```


# `r old_names[5]`

```{r}
# JN: more manual cleaning could be useful here
major_topics = unlist(str_split(x$major_topic, pattern = ","))
major_topics = str_trim(major_topics)
major_topics = str_to_lower(major_topics)
major_topics_df = data.frame(major_topic = major_topics)
# major_topic
ggplot(major_topics_df, aes(y = fct_infreq(major_topic))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[5])
```


# `r old_names[6]`

```{r}
# JN: more manual cleaning could be useful here
important_tasks = unlist(str_split(x$important_tasks, pattern = ","))
important_tasks = str_trim(important_tasks)
important_tasks = str_to_lower(important_tasks)
important_tasks_df = data.frame(important_tasks = important_tasks)

# important_tasks
ggplot(important_tasks_df, aes(y = fct_infreq(important_tasks))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[6])
```

# `r old_names[7]`

```{r}
# data_model
ggplot(x, aes(y = fct_infreq(data_model))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[7])
```

# `r old_names[8]`

```{r}
# JN: more manual cleaning could be useful here
r_packages = unlist(str_split(x$r_packages, pattern = ","))
r_packages = unlist(str_split(r_packages, pattern = ";"))
r_packages = unlist(str_split(r_packages, pattern = "\\*"))
r_packages = str_trim(r_packages)
# r_packages = str_to_lower(r_packages)
r_packages_df = data.frame(r_package = r_packages)

# r_packages
ggplot(r_packages_df, aes(y = fct_infreq(r_package))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[8])
```

# `r old_names[9]`

```{r}
# own_package
ggplot(x, aes(y = fct_infreq(own_package))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[9])
```

# `r old_names[10]`

```{r}
# own_package_location
ggplot(drop_na(x, own_package_location),
       aes(y = fct_infreq(own_package_location))) +
    geom_bar() +
    labs(x = "Count", y = NULL, title = old_names[10])
```

# `r old_names[11]`

```{r}
missing_methods = na.omit(x$missing_methods)
missing_methods_df = data.frame(id = seq_along(missing_methods),
                         missing_method = missing_methods)
knitr::kable(missing_methods_df)
```

# `r old_names[12]`

```{r}
# usefulness
x$usefulness = factor(x$usefulness, levels = as.character(c(1:5)))
x$usefulness = fct_rev(fct_infreq(x$usefulness))
ggplot(x, aes(x = usefulness)) +
  geom_bar() +
  scale_x_discrete(drop = FALSE) +
  labs(x = "Count", y = NULL, title = old_names[10])
```


# `r old_names[13]`

```{r}
comments = na.omit(x$comments)
comments_df = data.frame(id = seq_along(comments),
                         comment = comments)
knitr::kable(comments_df)
```

