---
title: Open source landscape ecology tools
# subtitle: Do you have a subtitle? If so, write it here
# titlerunning: Open source landscape ecology tools
# authorrunning: Short form of author list if too long for running head
thanks: | 
    Grants or other notes about the article that should go on the front 
    page should be placed here. General acknowledgments should be placed at the
    end of the article.
authors: 
- name: Maximillian H.K. Hesselbarth
  address: Department of Ecosystem Modelling, University of Goettingen, Buesgenweg 4, 37077 Goettingen, Germany
  email: maximilian.hesselbarth@uni-goettingen.de
- name: Jakub Nowosad
  address: Institute of Geoecology and Geoinformation, Adam Mickiewicz University, Krygowskiego 10, 61-680 Poznan, Poland
  email: nowosad.jakub@gmail.com
- name: Author 3
  address: Adress author 3
  email: E-Mail author 3
- name: ...
  address: ...
  email: ...
keywords:
- keyword 1
- keyword 2
- keyword 3
- keyword 4
- ...
abstract: |
  max. (200 words) Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract Abstract
bibliography: bibliography.bib
bibstyle: spphys # bibstyle options spbasic(default), spphys, spmpsci
preamble: | 
  \usepackage{caption}
  \usepackage{ltablex}
  \usepackage{lscape}
  \usepackage{multirow}
output: rticles::springer_article
editor_options: 
  chunk_output_type: console
---

# Introduction {#sec:intro}

## A short introduction to landscape ecology {#sec:landscape_ecology}

Landscape ecology focuses on how ecological processes are influenced and modified by the heterogeneous landscapes they occur in and simultaneously how the ecological processes themselves influence the landscapes \cite{Turner1989,Turner2005,With2019}. In this context, landscape ecology considers, besides others, i) spatial and temporal dynamics of heterogeneous landscapes, ii) interactions, fluxes and exchange within these landscapes, iii) how the landscapes influence ecological processes (and vice versa) and lastly iv) how to manage these heterogeneous landscapes \cite{Risser1984,Turner1989}.

<!-- MH: Not super happy with the list i) - iv) -->

While human activities have altered the landscapes for millennials \cite{Ellis2011,Ellis2015}, in the past centuries the effects of humans on landscapes have increased to an unknown high, known as the the Anthropocene \cite{Crutzen2002}. Today, almost all landscapes are directly or indirectly influenced by human activities \cite{Vitousek1997}. Thus, understanding the complex interactions between landscapes and ecological processes becomes increasingly important \cite{With2019}. 

Because landscapes are defined as mosaics of different land covers, ecosystems, habitat types, or land uses \cite{Forman1986,Forman1995,Wiens1995}, spatial context is important and ecological processes will vary spatially \cite{With2019}. Related to this, the importance of scale was already raised decades ago \cite{Wiens1989,Levin1992,Jelinski1996} and is still of relevance until today \cite{Simova2012,Estes2018}. Thus, in contrast to many other sub-disciplines of ecology, landscape ecology emphasizes especially spatial patterns to a high degree \cite{Risser1984}. Consequently, the field of landscape ecology relies on software to preprocess, modify, model, analyze and visualize spatial data.

<!-- MH: Do we need some more basic introduction to landscape ecology? -->

## Open-source software and R {#sec:open_source}

Software to manage and analyze data becomes increasingly important in modern scientific research \cite{Wilson2014} and many scientific studies would not have been possible without open-source software \cite{Prlic2012}. Open-source software includes all software which is released under a license that allows to freely use, modify and distribute the software \cite{St.Laurent2008}. Open-source software development has many advantages, such as fast innovation, transparency and reliability as well as longevity, mainly due to many diverse contributors \cite{vonKrogh2006,St.Laurent2008}. Additionally, the use of open-source software facilitates (computational) reproducibility and can allow a better understanding of the methodology \cite{Prlic2012,Powers2019}. Lastly, open-source software allows other scientists to reuse code and not "reinvent the wheel" \cite{Prlic2012} and to customize existing software to their specific needs \cite{Steiniger2009}. 

One example of a successful open-source project is the *R* programming language and its *Comprehensive R Archive Network* (CRAN) for extensions (also called packages) \cite{RCoreTeam2019}. Firstly introduced in 1995 \cite{Smith2016}, today the programming language is among the most popular programming languages, especially in ecology \cite{Lai2019}. Originally introduced as a statistical programming language, a growing body of packages designed to analyze spatial data subsequently emerged for the *R* programming language \cite{Bivand2006}. This is documented by the growing *CRAN Task View: Analysis of Spatial Data* \cite{Bivand2019a} and *CRAN Task View: Handling and Analyzing Spatio-Temporal Data* \cite{Pebesma2020} with currently almost 300 packages in total. The growing popularity of the *R* programming language for spatial data analysis and landscape ecology can also be seen by the increasing number of related textbooks \cite{Fletcher2019,Lovelace2019,Pebesma2019a}.

Even though many other open-source tools for landscape ecology exist \cite{QGISDevelopmentTeam2016,GRASSDevelopmentTeam2017,Porta2017}, in this review we are going to focus on tools implemented in the *R* programming language. Thus, in the first part we are going to try to give a comprehensive overview over existing *R* packages for landscape ecology. In the second part, we will identify topics for which *R* packages are currently missing to the best of our knowledge. For more general overviews see e.g. \cite{Jolma2008,Steiniger2009,Steiniger2009a,Istvan2012}.

# Existing packages {#sec:existing_packages}

<!-- MH: I went for a structure where in the first paragraph I briefly introduce the topic and then list the most common packages. -->

<!-- MH: Maybe we need to think about a table with the topics and the packages as a nice overview. Additionally, a figure where we show a typical workflow would be nice maybe -->

<!-- MH: What about packages that are not on CRAN anymore, e.g. adehabitat? -->

<!-- MH: Add references for all packages -->

## Basic spatial data

<!--MH: Short paragraph about scale; *grainchanger*; DOI: 10.1111/2041-210X.13177 -->

<!-- MH: landscapetools; DOI: 10.1111/2041-210X.13076 -->

## Creating maps

## Spatial regression
<!-- MH: Do we really want to include this? Not really a landscape ecology topic but rather (geo) spatial stats I would argue -->

## Ecological analysis {#sec:ecological_analysis}

#### Landscape metrics {#sec:landscape_metrics}

One of the most fundamental steps of landscape ecology is to describe and quantify landscape characteristics \cite{Turner2005,Lausch2015}. For discrete land cover classes the composition (number and abundance) and configuration (spatial arrangement) of the landscape is often described using landscape metrics \cite{Gustafson1998,Uuemaa2009,Uuemaa2013,Gustafson2019}. These metrics allow to compare different landscapes, quantify temporal and spatial landscape changes and investigate interactions between landscape characteristics and ecological processes \cite{Uuemaa2009}. 

The use of landscape metrics was heavily facilitated by the introduction of the *FRAGSTATS* software \cite{McGarigal2012}, firstly published in 1995 \cite{Kupfer2012,Gustafson2019}. However, *FRAGSTATS* is not not open-source software (however it is free to download at the developers' homepage), which restricts transparency and reproducibility. To provide a truly open-source solution to calculate landscape metrics, recently the *landscapemetrics* package \cite{Hesselbarth2019a} was developed. The package allows to calculate the most widely used landscape metrics in a transparent and reproducible workflow within the *R* environment.  Additionally, the *belg* packages allows to calculate the Boltzmann entropy of a landscape gradient \cite{Nowosad2019a}.

#### Species distribution modeling {#sec:SDM}

Species distribution modeling (SDM) analysis how landscape patterns (e.g. habitat suitability, resources availability, etc.) influence and determine the patterns of species distribution, mainly to infer ecological processes and predict future species distributions \cite{Wiersma2011}. Originated in the 1970s, SDM has experienced numerous methodological advancement and a numerous body of literature exists today \cite{Zimmermann2010}. Additionally, textbooks introducing  basic concepts of SDM in *R* exists \cite{Guisan2017,Fletcher2019}.

Because the used modeling approaches are diverse \cite{Hooten2011,Kerr2011,Fletcher2019}, there is also a large number of *R* packages used for SDMs. Popular approaches and packages include generalized linear models using e.g. the *stats* package; generalized additive models using e.g.the *mgcv* or *lme4* package; classification and regression trees (CART) using e.g. the *rpart*, *randomForest* or *ranger* package or multivariate data analysis using e.g. the *ade4* or *vegan* package. Of course, also packages specifically designed for SDM exists. This includes the *dismo*, *sdm*, *ecospat*, *biomod2* and *PresenceAbsence* packages.

#### Connectivity {#sec:connectivity}
Connectivity is one of the core elements of landscape structure \cite{Taylor1993} and thus one of the core concepts of landscape ecology \cite{With2019}. Landscape connectivity describes how landscape characteristics facilitate or hinder the movement of species \cite{Tischendorf2000} or other aspects of mobility, such as dispersal, gene or nutrient flow \cite{With2019}. While structural connectivity focuses only on landscape characteristics (e.g. movement corridors, barriers, etc.), functional connectivity also includes behavior characteristics of the species \cite{Tischendorf2000,With2019}. 

Given its wide concept, many different measures of connectivity exists \cite{Kindlmann2008}. On patch level structural connectivity can be measured using nearest-neighbor distances or characterizations of the patch neighborhood (e.g. amount of suitable habitat) \cite{Kindlmann2008,With2019}. Such measures are provided within the *landscapemetrics* package (see \ref{sec:landscape_metrics}). Another way to describe connectivity is based on graph theory with the advantages that also functional connectivity can be included \cite{Kindlmann2008}. In graph theory  \cite{Laita2011} landscapes are described by nodes (i.e. habitat patches) connected by and functional connections called links \cite{Laita2011}. The *grainscape* package \cite{Chubaty2020} provides a tool to model connectivity based on spatially explicit networks. More general, the *igraph* packages \cite{Csardi2006} provides functionality related to graph theory. Resistance surfaces and least-cost paths are another tool to model functional connectivity. The resistance surface describes effects of facilitating or hindering characteristics of the landscape for an organism moving within it \cite{Adriaensen2003}. Least-cost paths can be calculated using the *gdistance* package \cite{vanEtten2017}. Absorbing Markov chains that combines random walk theory and mortality based on the landscape characteristics \cite{Fletcher2019a} and is provided by the recently published *samc* package \cite{Marx2020}.

#### Landscape genetics {#sec:landscape_genetics}

Landscape genetics investigates how characteristics of landscapes interact with gene flow, genetic drift and selection \cite{Manel2003}. Such insights improve our understanding of metapopulation dynamics, speciation, species’ distributions and conservation \cite{Storfer2007}. By explicitly including characteristics of landscape, landscape genetics is a way more realistic way of analysis than e.g. metapopulation genetics \cite{Holderegger2006}. As a result of its interdisciplinary, landscape genetics combines methods from different disciplines including landscape ecology, spatial statistics, geography and population genetics \cite{Storfer2007}.

<!-- MH: Work-in-Progress -->
<!-- MH: General population genetics -->
<!-- MH: Isolation by resistance  -->
<!-- MH: Bayesian Genetic Clustering -->
<!-- MH: Multivariate Ordination Techniques -->

Since describing connectivity between two locations is one of the fundamental steps of landscape genetics, all packages useful for connectivity (see \ref{sec:landscape_genetics}) are also of importance for landscape genetics. Further functionality for landscape genetics can be found in the *graphs4lg* \cite{Savary2020}, *PopGenReport* \cite{Adamack2014,Gruber2015}, or *HierDpart* packages \cite{Qin2019}.

#### Neutral landscape models {#sec:NLM}
Neutral landscape models are used to create structured landscapes in the absence of specific ecological and landscape processes as null models against which hypotheses including specific ecological and landscape processes can be tested statistically \cite{Gardner1987,With1997}. Because neutral landscape models are not based on ecological and landscape process, many different generic algorithms to create landscapes can be found (for a comprehensive list, see \cite{Sciaini2018}). 

Currently, to our knowledge, only one *R* packages exists that allows the use of neutral landscapes. Using a wide collection of algorithms, the *NLMR* package \cite{Sciaini2018} provides framework to simulate neutral landscape rasters. 

\begin{landscape}

\begin{center}
  \begin{table}
    \begin{tabularx}{0.9\linewidth}{XXXX}
      \caption{Overview of commonly used \textit{R} packages for landscape ecology. Packages are sorted by their major application topic. Only packages especially for spatial data and landscape ecology are included. SDM = Species distribution modeling; NLM = Neutral landscape model} \\
      \hline
      Topic & Package & Description & Source \\
      \hline
      \multirow{5}{*}{Spatial data} & \textit{raster} & Methods for raster data & \cite{Hijmans2019} \\
      & \textit{stars} & Methods for spatiotemporal arrays (raster and vector data cubes) & \cite{Pebesma2019} \\
      & \textit{sp} & Methods for mainly vector data & \cite{Pebesma2005,Bivand2013} \\
      & \textit{sf} & Methods for vector data as simple features & \cite{Pebesma2018} \\
      & \textit{landscapetools} & Utility functions for landscape analysis & \cite{Sciaini2018} \\
      \hline
      \multirow{3}{*}{Creating maps} & \textit{tmap} & xxx & xxx \\
      & \textit{mapview} & xxx & xxx \\
      & \textit{leaflet} & xxx & xxx \\
      \hline
      \multirow{2}{*}{Landscape metrics} & \textit{landscapemetrics} & Calculates landscape metrics for categorical land cover maps & \cite{Hesselbarth2019a} \\
      & \textit{belg} & Calculates the Boltzmann entropy of a landscape gradient & \cite{Nowosad2019a} \\
      \hline
      \multirow{5}{*}{SDM} & \textit{dismo} & xxx & xxx \\
      & \textit{sdm} & xxx & xxx \\
      & \textit{ecospat} & xxx & xxx \\
      & \textit{biomod2} & xxx & xxx \\
      & \textit{PresenceAbsence} & xxx & xxx \\
      \hline
      \multirow{3}{*}{Connectivity} & \textit{grainscape} & xxx & \cite{Chubaty2020} \\
      & \textit{gdistance} & xxx & \cite{vanEtten2017} \\
      & \textit{samc} & xxx & \cite{Marx2020} \\
      \hline
      \multirow{3}{*}{Landscape genetics} & \textit{graphs4lg} & xxx & \cite{Savary2020} \\
      & \textit{PopGenReport} & xxx & \cite{Adamack2014,Gruber2015} \\
      & \textit{HierDpart} & xxx & \cite{Qin2019} \\
      \hline
      NLM & \textit{NLMR} & xxx & \cite{Sciaini2018} \\
      \hline
    \end{tabularx}
  \end{table}
\end{center}

\end{landscape}

<!-- # Missing packages -->

<!-- Another widely used SDM approach uses the concept of maximum entropy \cite{Phillips2006,Fletcher2019}. However, currently the *maxent* package is not available on *CRAN* anymore. -->
